name: DREAM Deployment

on:
  release:
    types:
      - created

jobs:
  dist_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt -yq update
        sudo apt install -yq --no-install-recommends libfftw3-dev

    # Sets up MATLAB on the GitHub Actions runner
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_MEX=on -DBUILD_OCT=off

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload DREAM Matlab Linux

      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/build/*.mexa64
        asset_name: oq-${{ github.event.release.tag_name }}-matlab-linux-x86_64
        asset_content_type: binary/octet-stream
