name: DREAM Deployment

on:
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  deploy-linux-matlab:

    runs-on: ubuntu-latest

    #outputs:
    #  version: ${{ steps.step_version.outputs.version }}
    #  upload_url: ${{ steps.step_upload_url.outputs.upload_url }}

    #  - id: step_version
    #    run: echo "::set-output name=version::${{ steps.package_version.outputs.version }}"

    #  - id: step_upload_url
    #    run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"

    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt -yq update
        sudo apt install -yq --no-install-recommends libfftw3-dev

    # Sets up MATLAB on the GitHub Actions runner
    - name: Setup MATLAB
      uses: matlab-actions/setup-matlab@v1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="-O3" -DBUILD_MEX=on -DBUILD_OCT=off

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload DREAM Matlab Linux
      id: create_release
      uses: shogo82148/actions-create-release@v1

    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/build/*.mexa64
        asset_name: ${{ github.event.release.tag_name }}-matlab-linux-x86_64

     #   uses: actions/upload-release-asset@v1.0.2
     # env:
     #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     # with:
     #   #upload_url: ${{ github.event.release.upload_url }}
     #   upload_url: ${{ needs.deploy-linux-matlab.outputs.upload_url }}
     #   asset_path: ${{github.workspace}}/build/*.mexa64
     #   #asset_name: oq-${{ github.event.release.tag_name }}-matlab-linux-x86_64
     #   asset_name: ${{ needs.deploy-linux-matlab.outputs.version }}-matlab-linux-x86_64
     #   asset_content_type: binary/octet-stream
